name: flutter_youtube_extractor
description: A new Flutter plugin for getting youtube media link.
version: 1.0.0
author: TanLNM <tanlnm@sendo.vn>
homepage: https://flutter.io

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        androidX: true
        package: io.fluttervn.flutteryoutubeextractor
        pluginClass: FlutterYoutubeExtractorPlugin
      ios:
        pluginClass: FlutterYoutubeExtractorPlugin

